version: '3'

services:
  # Layanan untuk aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "89:80" # Port host:port kontainer web server
    volumes:
      - .:/var/www/html # Mount direktori proyek ke direktori web server di dalam kontainer

  # Layanan untuk database MySQL 5.7
  db:
    image: mysql:5.7
    ports:
      - "3308:3306" # Port host:port kontainer database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: db_remun_new
